basecamp:
  project_id: 3424579
  domain: flatsoft.grouphub.com
  username: test
  password: test

lighthouse:
  account: flatsoft
  token: test
  resolved_states: [accepted, resolved, invalid, hold]
